### ISSUE TITLE
Uploading Chapters Broken

### ISSUE THREAD

**Issue by lehitoskin** [RamuneDeveloper/Ramune#4]
I pulled from the latest commit and now uploading chapters is broken. Looks like it's related to the new code about Volume information:

```
/home/lehi/prog/js/Ramune/node_modules/pg-protocol/dist/parser.js:278
            : new messages_1.DatabaseError(messageValue, length, name);
              ^

error: column "volume_id" of relation "uploads" does not exist
    at Parser.parseErrorMessage (/home/lehi/prog/js/Ramune/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/lehi/prog/js/Ramune/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/lehi/prog/js/Ramune/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/lehi/prog/js/Ramune/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 129,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '32',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1034',
  routine: 'checkInsertTargets'
}
Program node server.js exited with code 1
```

**Comment by RamuneDeveloper** [comment]
I'd make sure you've run the latest migrations; `db-migrate up`

**Comment by lehitoskin** [comment]
Ah-ha. There we go. Everything's working how it should be now.
